### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by eugenezabolotny** [smalot/pdfparser#169]
Hi, I have a memory leak when parsing files like this one in this test code:
```
<?php

include __DIR__ . '/../vendor/autoload.php';


$input = 'http://www.zoda.gov.ua//files/WP_Article_File/original/000077/77073.pdf';

$parser = new \Smalot\PdfParser\Parser();
$pdf    = $parser->parseFile( $input );
$text   = $pdf->getText();

$path_parts = pathinfo( $input );
$filename   = $path_parts['filename'];
$output     = './pdf/' . $filename . '.txt';

file_put_contents( $output, $text );
```

adds a few megabytes of memory to use every second until the memory runs out.
Can you help me fix it, please?

**Comment by nedvajz** [comment]
Probably outdated, but if somebody else has same issue.   
https://github.com/smalot/pdfparser/issues/104#issuecomment-241813856

**Comment by eugenezabolotny** [comment]
A bit outdated, thank you ) But maybe can be useful for someone else

**Comment by Connum** [comment]
Three years on, I can parse that PDF file with the current master quite fast, without any memory issues.
@eugenezabolotny, can you confirm that this issue seems to have vanished with the code changes over time?

I used `memory_get_usage()` as suggested in #104, and it uses ~10 MB. However, I don't know whether that's expected from decoding a PDF of around 400 KB of size or not. It doesn't seem way too high to me.

**Comment by eugenezabolotny** [comment]
Thanks for your answer @Connum .
I'm not able to test it in near future. Anyway, I think you can close this issue if you haven't experienced the described problem.

**Comment by k00ni** [comment]
Thank you for the feedback.
