### ISSUE TITLE
How to handle outdated/abandoned lib "tecnickcom/tcpdf"?

### ISSUE THREAD

**Issue by k00ni** [smalot/pdfparser#291]
We use `tecnickcom/tcpdf` which seems **abandoned** according to:

https://github.com/tecnickcom/tcpdf

> A new version of this library is under development at https://github.com/tecnickcom/tc-lib-pdf and as a consequence this version will not receive any additional development or support. This version should be considered obsolete, new projects should use the new version as soon it will become stable.

But its successor `tc-lib-pdf` is not ready yet:

> UPDATE: CURRENTLY ALL THE DEPENDENCY LIBRARIES ARE ALMOST COMPLETE BUT THE CORE LIBRARY STILL REQUIRES A SIGNIFICANT AMOUNT OF WORK TO BE COMPLETED.

... and is not actively developed. There are voices to help out (https://github.com/tecnickcom/tc-lib-pdf/issues/53), but nothing happened so far.

How much is this library relying on tecnickcom/tcpdf?

**Comment by j0k3r** [comment]
Well, that readme was rewritten in 2016.

https://github.com/tecnickcom/TCPDF/commit/009f2304c3a9c8152b89a5321a8825f250911dc3#diff-04c6e90faac2675aa89e2176d2eec7d8

Since then, a lot of commit have been added by the maintainer.
But I agree, it’s not actively maintain.

I haven’t enough background in using PDFParser to act if we should remove it or not.

**Comment by k00ni** [comment]
@smalot: Can you tell us how far tcpdf is integrated in pdfparser?
