### ISSUE TITLE
v0.15.1

### ISSUE THREAD

**Issue by j0k3r** [smalot/pdfparser#298]
I've created a draft for a new small release v0.15.1

~~https://github.com/smalot/pdfparser/releases/tag/untagged-609f95c6d1348ad7df32~~

@smalot, @k00ni, @amooij are you ok with it?

**Comment by k00ni** [comment]
I am mostly OK with it.

But, i would like to name the release with the version rather than some text. That is more helpful if you run into problems with a certain version and want to check releases.

If we keep the text in the title, we should at least put the version the beginning of the description and make it clearly visible. Currently no version information at all.

**Comment by j0k3r** [comment]
I’ve edited the draft and removed the custom title

**Comment by k00ni** [comment]
Looks good :+1:
