### ISSUE TITLE
"File May Be Secure" Error

### ISSUE THREAD

**Issue by jlomeo** [smalot/pdfparser#373]
Hi All,
I use PDF Parser to parse court opinions in PDF from http://www.cafc.uscourts.gov/opinions-orders 
Recently (seemingly due to a change in PDF formatting from cafc), I started getting the error that the PDF cannot be parsed because the file may be secure.  After speaking with @smalot, I was told these files should not be getting this error.  One of the files is: http://www.cafc.uscourts.gov/sites/default/files/opinions-orders/19-2293.OPINION.12-4-2020_1696173.pdf

The document is not in fact secure and hopefully we can get it working with PDF parser.  Thanks all for your hard work on this great software.

Jim

**Comment by roalvesrj** [comment]
Hi @jlomeo ,
I share your problem, however, mine is with bank files, until a few months ago the files were generated in version 1.4, however, now they use version 1.5 and apparently PDFParse has some problem. Looking at other problems here, I saw that people use qPDF to "solve" the file problem, where after going through the program it is read normally. Well, I made contact with the people of qPDF, because I wanted to put it in the routine of my script to "correct" and then follow the processing, and I had some feedbacks from the people there:

> Regarding PDFParse not accepting 1.5 files, I can only guess what the issue might be. Perhaps it doesn't support 256-bit encryption, or perhaps it doesn't support object streams, or maybe it just doesn't like the version number.

@k00ni I don't know if the comment from the qPDF staff can help with anything
