### ISSUE TITLE
Duplicating numbers and problem with whitespaces

### ISSUE THREAD

**Issue by ScreamDev1** [smalot/pdfparser#464]
Hi, i have some issues with parsing pdf in Russia. First of all it's some problem with witespaces and also for some values of numeric i can see dupicates in parsed text. Attaching pdf and some screenshots, Thanks
![Screenshot 2021-10-06 at 03-36-46 Demo PDF Parser](https://user-images.githubusercontent.com/37838306/136122827-03ff4e90-4b7b-4e3e-88b3-a3864253e747.png)
[obj39453_pd32-000296.pdf](https://github.com/smalot/pdfparser/files/7290042/obj39453_pd32-000296.pdf)

**Comment by GreyWyvern** [comment]
I believe the "duplicate" numbers here are because the document is overprinting them to make the bold. Perhaps because it doesn't have a bold font? Regardless, the duplicated numbers and text all show up bold in the PDF. Copy-pasting from Adobe only copies one of them though so it's smart enough to do that?

Here's one of the "duplicated" sections:

```
BT
/F7 12 Tf
1 0 0 -1 0 0 Tm
456 -584 Td
<002D> Tj
8 0 Td
<0048> Tj
8 0 Td
<0046> Tj
8 0 Td
<0003> Tj
1 0 0 -1 0 0 Tm
/Span << /ActualText <> >> BDC
455.500000 -584 Td
<002D> Tj
8 0 Td
<0048> Tj
8 0 Td
<0046> Tj
8 0 Td
<0003> Tj
EMC
ET
```

First it sets the text matrix to `1 0 0 -1 0 0` then positions it at `456 -584` and prints four characters. Then it resets the text matrix to `1 0 0 -1 0 0` and positions it **almost** on top of the previous start position, just a fraction to the right (or left?) at `455.500000 -584` to make the characters fatter and thus bolder. Then it prints the same four characters. Overprinting.
