### ISSUE TITLE
Call for testers: Please test our latest release candidate v1.2.0-RC2

### ISSUE THREAD

**Issue by k00ni** [smalot/pdfparser#468]
## What is going on?

Currently we have the situation that this library grows slowly but steady with mostly foreign contributions. I opened this issue because we merged #440 and #459. Both added explicit parameter and return types. We follow Semantic Versioning and are required to increase major version, but in my opinion almost all of these changes were internally. Because of our limited time resources I decided to try middle way: release it regardless of possible backward compatibility breaks, but mark it as a release candidate and include the community to see if there are problems left.

## How can you help?

It would be great if some of you could lend us a hand and test our latest release candidate:

https://github.com/smalot/pdfparser/releases/tag/v1.2.0-RC2

Just do the things you normally do with the library and check if problems occur. If you get errors, please post a comment here with a basic description, error message and if possible the PDF you used. If everything works as expected, please up vote this issue. This way there is some orientation for us.

**Thank you for your help!**

Ref #465

CC @PrinsFrank @j0k3r @smalot @izabala

---

### FAQ

**Question** Do I have to use the zip file as it is in https://github.com/smalot/pdfparser/releases, or we will use a branch or a pull request for this?
**Answer** You can use the way you prefer (composer, download ZIP, ...). If you find any errors/issues please create a pull request against `master` branch.

**Comment by PrinsFrank** [comment]
We have been running the master branch and subsequent forked branches with fixes for typeErrors on production for over a month now since we needed @Nickmanbear 's fix in #457 , and all my recent PRs are a result of bugs we encountered related to the recent types change. I don't think we use every functionality of this package, but parse quite a variety of different kinds of pdfs. 

We have seen some more silently failing parse attempts recently. Wether those are due to recursion, them being very large files (hundreds of megabytes), because of the type changes or because we are watching more closely I am not sure yet. I am currently unavailable due to a broken hand and being sick, but hopefully will be able to provide more info in the upcoming week. I will keep you guys updated.

**Comment by k00ni** [comment]
## Update 18th Oct. 2021

Merged:
* #455
* #466

**New release:** 1.2.0-RC2

https://github.com/smalot/pdfparser/releases/tag/v1.2.0-RC2

---

Thank you for your quick replies.

@izabala wrote:
> One question do I have to use the zip file as it is in https://github.com/smalot/pdfparser/releases/tag/v1.2.0-RC1, or we will use a branch or a pull request for this?

I updated my initial post with this question and an answer.

@izabala wrote:
> I soon as we finished with pull request #455, I may give a hand with this. I am busy, but I could spend a little time each day to test it.

That sounds great. I merged #455 to speed this up.

@PrinsFrank:
> [..] and all my recent PRs are a result of bugs we encountered related to the recent types change. We have seen some more silently failing parse attempts recently. Wether those are due to recursion, them being very large files (hundreds of megabytes), because of the type changes or because we are watching more closely I am not sure yet. 

That sounds worrisome, so its a good thing we have you guys on board also. All the best with your hand!

**Comment by k00ni** [comment]
Thank you guys for your effort and fast response!

**Comment by k00ni** [comment]
**Small update:** We currently received feedback from two people. I would like to keep this open for around 7-10 days. If there aren't any errors reported I will release `1.2.0`.

**Comment by k00ni** [comment]
Replaced by #480
