### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by likemusic** [smalot/pdfparser#498]
This library has some helpfull config options and methods that not covered in documentation ($cfg's 'ignore_filter_decoding_errors' and 'ignore_missing_filter_decoders' options, Page's `getDataTm()` and `getTextXY()` methods e.t.c.).

**Comment by k00ni** [comment]
That is on my TODO list for a while and I plan to propose some improvements in January 2022.

**Comment by Reqrefusion** [comment]
Hello, I also made some suggestions about documentation before. I thought it would be good to solve this problem with the wiki page. This is quite appropriate, especially considering the way the project is progressing. I invite you to contribute to the wiki.

**Comment by k00ni** [comment]
Thank you for your contributions here @Reqrefusion.

I personally don't like usage of our Wiki, because it can be changed by everyone (with no way to approve/decline changes). My suggestion would be to utilize Markdown-files (like DEVELOPER.md), because we can use pull requests. 

Its sad that @smalot is off for a while again, because documentation at pdfparser.org's is also outdated and we should discuss a way how to organize documentation in general.

**Comment by k00ni** [comment]
Note: include #505 when updating documentation.

**Comment by Reqrefusion** [comment]
- [ ] Preparing a more detailed briefing for the config.
I found this necessary because @rubenvanerk  provides solutions to some problems by using the config feature. He had already made an addition in this direction on the [wiki page](https://github.com/smalot/pdfparser/wiki/Use). I also added a table. But still work in process.

**Comment by rubenvanerk** [comment]
Maybe it's also an idea to have a 'Common problems' section with possible solutions.

**Comment by k00ni** [comment]
Thanks again for the work on the wiki folks.

After #500 is done (hopefully end of January) we should focus on documentation. Until then, is there anything "missing" in documentation and/or wiki which you would like to include?

Would it be sufficient to just "copy" the wiki and merge it into the README.md with a few style improvements?

**Comment by rubenvanerk** [comment]
A section with limitations would also be useful. Like parsing form fields.

Adding all the wiki documentation to the readme might be a bit much, but I think it could work.

**Comment by k00ni** [comment]
I haven't forgotten but I am very busy currently. If anyone want to propose something via pull request, feel free.

My approach would be to split (wiki) documentation into different files in `doc` folder. I would also remove some stuff from README.md and maybe update other info.
