### ISSUE TITLE
Empty page, nothing parsed

### ISSUE THREAD

**Issue by rvdsarr** [smalot/pdfparser#61]
Hey guys,

I have a PDF, and whenever I try to parse it, it comes back as an string with a few whitespaces. Same happends on the demo page. 

I'd like to share the PDF, but just with the dev's if thats alright. 

Thanks.

Roy

**Comment by AlexKovalevych** [comment]
Having similar problem. After debug i figured out that it silently failed here:

```
 [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: iconv(): Wrong charset, conversion from `Windows-1252' to `UTF-8//TRANSLIT//IGNORE' is not allowed
```

Trace:

```
Exception trace:
 () at /var/www/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:498
 Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
 iconv() at /var/www/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:498
 Smalot\PdfParser\Font->decodeContent() at /var/www/vendor/smalot/pdfparser/src/Smalot/PdfParser/Font.php:386
 Smalot\PdfParser\Font->decodeText() at /var/www/vendor/smalot/pdfparser/src/Smalot/PdfParser/Object.php:318
 Smalot\PdfParser\Object->getText() at /var/www/vendor/smalot/pdfparser/src/Smalot/PdfParser/Page.php:217
```

Not sure what to do with that error, yet..

**Comment by gud** [comment]
I've the same problem. Each time a pdf file contains at least one blank page the parser stop and nothing is returned to the caller script, no error either. This is really blocking because it is not possible to ignore the file neither taking any action to bypass the file.

**Comment by AlexKovalevych** [comment]
I figured out the problem - i've used alpine `php-iconv` package which is obviously not working well. After i built from the source `libiconv` library and rebuilt `php-iconv` everything worked well.

**Comment by gud** [comment]
This not works on an apache 2.4.9 /php 5.5.12 server on windows 7 (WAMP) BUT works well on a Linux server with PHP Version 5.3.29

**Comment by mplx** [comment]
I ran into the same problem when switching from a Debian host to a alpine based docker container.

The `iconv()` function relies heavily on the functions provided by the OS; i.e. Debian uses glibc whilst Alpine uses musl libc - [musl's implementation of iconv](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc) is very slim and does not support `//TRANSLIT` and `//IGNORE`.

There are five calls to `iconv()` in `Font.php` which fail on systems where `//TRANSLIT` and `//IGNORE` are not supported (if they weren't silenced via error control operator `@` you would receive a `PHP Notice:  iconv(): Wrong charset, conversion from 'Windows-1252' to 'UTF-8//TRANSLIT//IGNORE' is not allowed`). When running atomu on those systems two tests will fail (empty string instead of expected utf8 string).

Possible solutions:

1. remove `//TRANSLIT` and `//IGNORE` ([PR ready](https://github.com/mplx/pdfparser/tree/fix/musllibc)). What are the sideeffects of this?

2. use `//TRANSLIT//IGNORE` and check return value; if failed then `iconv()` a second time without (i.e. `if ($decoded === false) { $decoded = iconv(...); }`). Sideeffects?

3. switch from `ext-iconv` to `ext-mbstring` (`mb_convert_encoding`)

**Comment by mplx** [comment]
I've looked a bit further into this issue...

pdfparser uses iconv to convert to UTF-8 from Windows-1252 and MacRoman. As both character sets are defacto available complete in UTF8 the iconv parameters `//LITERAL` and `//IGNORE` should not be necessary, at least under the assumption that input data is either valid UTF8, valid Win1252 or valid MacRoman.

* Win1252: there are 5 character codes unmapped to utf8 but as they are not used by win1252 anyway it shouldn't matter. See ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT

* MacRoman: unmapped are control characters 00x-0x1F und unused 0x7F - ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/ROMAN.TXT

However as pdfparser [already uses mbstring lib](https://github.com/smalot/pdfparser/blob/master/src/Smalot/PdfParser/Font.php#L371) to detect the encoding (`mb_check_encoding`) and mbstring also provides functionality to convert char encodings it might be the better solution to replace `iconv()` with `mb_convert_encoding()` and reduce dependencies.

Ready for PR: [fix/mbstring](https://github.com/mplx/pdfparser/tree/fix/mbstring)
