### ISSUE TITLE
Fault tolerance

### ISSUE THREAD

**Issue by interleave** [smalot/pdfparser#64]
We're testing pdfparse in batch mode to index pdf files, which works fine, until it encounters only the slightest error - it throws an exception and quits immediately. IMHO the result of trying to extract text from a damaged or unsupported pdf file should just be "false" or plain nothing. But quitting the script is disastrous in our case because pdfparse is used in a much larger context .. if the script dies, everything dies. Is there anything I can do about that? Obviously is easy to adjust the code, but I don't want to for compatibility reasons.

**Comment by mcordingley** [comment]
Can't you just wrap the call into a `try` block and assign the empty value of your choosing in a `catch`?

**Comment by Connum** [comment]
As there has been no answer in more than 4 years, and using `try/catch` seems like the obious solution, I'd say this issue can be closed.

**Comment by k00ni** [comment]
> IMHO the result of trying to extract text from a damaged or unsupported pdf file should just be "false" or plain nothing. But quitting the script is disastrous in our case because pdfparse is used in a much larger context .. if the script dies, everything dies. Is there anything I can do about that?

In my opinion an exception is way more handy than `false` or `null` as return value in case of an error. You can catch it and handle it your way. Furthermore, you get an information *why* a PDF can't be parsed. If you only have `false` (or null), you have no information at all. Also throwing an exception is *not* quitting the script, its a basic mechanism in PHP actually. Sure, its basically the same as using `die()` in the end, but only if you don't catch them.

I am closing it, because its not an issue.

Thanks @Connum for the ping.
