### ISSUE TITLE
Want to remove page numbers eg: (page 1 of 2), when using getText( ), can I achieve that ? 

### ISSUE THREAD

**Issue by SwanHtet018** [smalot/pdfparser#662]
![image](https://github.com/smalot/pdfparser/assets/143389584/d1268c26-07d3-4b9b-a4fc-77dd6d9ff0e8)

Can I remove page numbers (eg.page 1 of 2) while using getText( ) ?

**Comment by k00ni** [comment]
That is out of scope of PDFParser, because it only (tries to) extract what is in the PDF. But you could solve this by using a regex together with preg_replace (https://www.php.net/manual/en/function.preg-replace.php) to remove unwanted sub strings.

Try something like this: `/Page\s+[0-9]+\s+of\s*[0-9]+/i` (untested)
