### ISSUE TITLE
Weird charcters parsed from pdf,

### ISSUE THREAD

**Issue by LCD344** [smalot/pdfparser#88]
I've been trying to get the text from a file like this https://pdonline.brisbane.qld.gov.au/masterviewui/cache/VvxFDshJTm.pdf

and all the text I am getting is weird "" characters - I tried utf8 decode but it didn't work. Is there anything to do about this?

**Comment by davispuh** [comment]
Try #257 PR maybe it's fixed there.

**Comment by Connum** [comment]
The linked PDF is no longer available, and Brisbane City Council seems to be so strict about who may access their data under which conditions, that I didn't even dare to accept their terms/disclaimer from abroad in order to get another PDF from there. 😅
Unless @LCD344 would like to provide a working PDF to test this 5 years on... I'd suggest that this issue should be closed.
